# this is an example telebot docker-compose file
version: '3'
services:

  crossroad:
    image: finnetrolle/choreo-crossroad:latest
    container_name: crossroad
    restart: always
    environment:
      - RABBIT_CONNECTION_HOSTNAME=vsxo.ru
      - SERVER_PORT=8000
    ports:
      - "8000:8000"

  passage_sber:
    image: finnetrolle/choreo-passage:latest
    container_name: passage_sber
    restart: always
    environment:
      - RABBIT_CONNECTION_HOSTNAME=vsxo.ru
      - SERVICE_NAME=sber
      - ADDITIONAL_READ_FROM=failover

#  passage_pochta:
#    image: finnetrolle/choreo-passage:latest
#    container_name: passage_pochta
#    restart: always
#    environment:
#      - RABBIT_CONNECTION_HOSTNAME=vsxo.ru
#      - SERVICE_NAME=pochta
#      - ADDITIONAL_READ_FROM=default

#  passage_gcs:
#    image: finnetrolle/choreo-passage:latest
#    container_name: passage_gcs
#    restart: always
#    environment:
#      - RABBIT_CONNECTION_HOSTNAME=vsxo.ru
#      - SERVICE_NAME=gcs
#      - ADDITIONAL_READ_FROM=